### ISSUE TITLE
bit and

### ISSUE THREAD

**Issue by zhaishengfu** [RodZill4/godot-goap#2]
hello, wonderful project, thanks for the project.
I have a question. you have this line in your code:
`return get_script().new((value & mask & (~effect.mask)) | (effect.value & effect.mask), mask | effect.mask)`

and In my opiniton, mask always contains value , so value & mask is always the same as value! that is , you can use following code to replace previous code.
`return get_script().new((value  & (~effect.mask)) | (effect.value), mask | effect.mask)`

Is this right?

**Comment by RodZill4** [comment]
No, mask does not alway contains value. Mask is the mask of properties that are assigned, value is their values. So properties that are set to 0 have 1 as mask and 0 as value.

**Comment by zhaishengfu** [comment]
Yes, may be I say it unclearly. What I mean is,
 **value & mask is always the same as value**
if value bit is 1, then mask bit must be 1. if value bit 0, mask bit can be 1 or 0. So
1 & 1  = 1,  0 &(anything) is 0
that is, 
 **value & mask is always the same as value**!

**Comment by RodZill4** [comment]
You're right, this operation is useless if value and mask are correctly set ("value and not mask" should be 0) which cannot be guaranteed. So if the user fails to define his action correctly, the state will still be correct.

**Comment by zhaishengfu** [comment]
ok got it.
